#!/bin/bash
set -e

FF_PROFILES_PATH=${FF_PROFILES_PATH:-$HOME/.mozilla/firefox/profiles.ini}

if [ -f $FF_PROFILES_PATH ]; then
    loaded_profiles=$(grep 'Name=' $FF_PROFILES_PATH | cut -d '=' -f 2)
    profiles=${loaded_profiles:-default}
else
    profiles=(default)
fi

profile_name=$(printf '%s\n' "${profiles[@]}" | dmenu)

exec firefox -P $profile_name $@

