#!/usr/bin/env bash
set -euo pipefail

FIREPROFILE_FF_BIN=${FIREPROFILE_FF_BIN:-firefox}
FF_PROFILES_PATH=${FF_PROFILES_PATH:-$HOME/.mozilla/firefox/profiles.ini}
FIREPROFILE_DMENU_CMD="${FIREPROFILE_DMENU_CMD:-dmenu}"
FIREPROFILE_DMENU_OPTS=${FIREPROFILE_DMENU_OPTS:-}

if [ -f $FF_PROFILES_PATH ]; then
    loaded_profiles=$(grep 'Name=' $FF_PROFILES_PATH | cut -d '=' -f 2)
    profiles=${loaded_profiles:-default}
else
    profiles=(default)
fi

profile_name=$(printf '%s\n' "${profiles[@]}" | "$FIREPROFILE_DMENU_CMD" $FIREPROFILE_DMENU_OPTS)

exec "$FIREPROFILE_FF_BIN" -P $profile_name $@
